### PR TITLE
OPSEXP-755: Update Nginx config

### PR DESCRIPTION
**Pull request by gavincornwell**
- Added the ability to disable ADW and sync service so we don't have to maintain a separate image for Community
- Migrated Bamboo build to Travis

### CODE REVIEW

**Comment by killerboot** [comment]
I added @aborroy as I know that he has done some work related to this topic in the past.

**Review by aborroy — APPROVED** [review]
LGTM
Basically this is the same approach I was using for https://github.com/aborroy/acs-proxy

**Comment by aborroy** [comment]
Disabling other services is also relevant for testing deployments and other scenarios where all the services are not required.

**Comment by gavincornwell** [comment]
Fair point @aborroy, I will enhance to allow disabling of other services too.

**Pull request merged**
